---
- name: mysql | Install MySQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: mysql | Create databases
  mysql_db: name={{ item }} state=present login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ mysql.database }}"
    - "{{ mysql.database_test }}"

- name: mysql | Create users
  mysql_user: name={{ mysql.user }} password={{ mysql.password }} priv={{ item }}.*:ALL append_privs=yes state=present login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ mysql.database }}"
    - "{{ mysql.database_test }}"
